openapi: 3.1.1
info:
  title: XAUAT.EduApi | v1
  version: 1.0.0
servers:
  - url: http://localhost:5216/
paths:
  /App:
    get:
      tags:
        - App
      parameters:
        - name: token
          in: query
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: string
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                type: string
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: string
  /Bus/{time}:
    get:
      tags:
        - Bus
      parameters:
        - name: time
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BusModel"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: string
  /Bus/NewData/{time}:
    get:
      tags:
        - Bus
      parameters:
        - name: time
          in: path
          required: true
          schema:
            type: string
        - name: loc
          in: query
          schema:
            type: string
            default: ALL
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BusModel"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: string
  /Bus/OldData/{time}:
    get:
      tags:
        - Bus
      parameters:
        - name: time
          in: path
          required: true
          schema:
            type: string
        - name: isShow
          in: query
          schema:
            type: boolean
            default: false
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BusModel"
  /Course:
    get:
      tags:
        - Course
      parameters:
        - name: studentId
          in: query
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CourseResultResponse"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CourseErrorResponse"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CourseErrorResponse"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CourseErrorResponse"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CourseErrorResponse"
        "502":
          description: Bad Gateway
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CourseErrorResponse"
  /Exam:
    get:
      tags:
        - Exam
      parameters:
        - name: studentId
          in: query
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ExamResponse"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                type: string
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: string
  /Info/Completion:
    get:
      tags:
        - Info
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: string
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                type: string
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: string
        "502":
          description: Bad Gateway
          content:
            application/json:
              schema:
                type: string
  /Info/Time:
    get:
      tags:
        - Info
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TimeModel"
  /Login:
    post:
      tags:
        - Login
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequest"
          application/*+json:
            schema:
              $ref: "#/components/schemas/LoginRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginResponse"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                type: string
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                type: string
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: string
  /Payment/{id}:
    get:
      tags:
        - Payment
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: string
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorWithMessageResponse"
        "503":
          description: Service Unavailable
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorWithMessageResponse"
  /Payment/{id}/turnover:
    get:
      tags:
        - Payment
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PaymentData"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorWithMessageResponse"
        "503":
          description: Service Unavailable
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorWithMessageResponse"
  /Playground:
    get:
      tags:
        - Playground
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: array
                  items:
                    type: array
                    items:
                      $ref: "#/components/schemas//additionalProperties"
  /Program:
    get:
      tags:
        - Program
      parameters:
        - name: id
          in: query
          schema:
            type: string
        - name: name
          in: query
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/PlanCourse"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                type: string
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: string
  /Program/GetDic:
    get:
      tags:
        - Program
      parameters:
        - name: id
          in: query
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: array
                  items:
                    $ref: "#/components/schemas/PlanCourse"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                type: string
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: string
  /Score/Semester:
    get:
      tags:
        - Score
      parameters:
        - name: studentId
          in: query
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SemesterResult"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                type: string
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /Score/ThisSemester:
    get:
      tags:
        - Score
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SemesterItem"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                type: string
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /Score:
    get:
      tags:
        - Score
      parameters:
        - name: studentId
          in: query
          schema:
            type: string
        - name: semester
          in: query
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ScoreResponse"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                type: string
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
components:
  schemas:
    BusItem:
      type: object
      properties:
        lineName:
          type: string
        description:
          type: string
        departureStation:
          type: string
        arrivalStation:
          type: string
        runTime:
          type: string
        arrivalStationTime:
          type: string
    BusModel:
      type: object
      properties:
        records:
          type: array
          items:
            $ref: "#/components/schemas/BusItem"
        total:
          pattern: ^-?(?:0|[1-9]\d*)$
          type:
            - integer
            - string
          format: int32
    CourseActivity:
      type: object
      properties:
        weekIndexes:
          type: array
          items:
            pattern: ^-?(?:0|[1-9]\d*)$
            type:
              - integer
              - string
            format: int32
        teachers:
          type: array
          items:
            type: string
        campus:
          type: string
        room:
          type: string
        courseName:
          type: string
        courseCode:
          type: string
        weekday:
          pattern: ^-?(?:0|[1-9]\d*)$
          type:
            - integer
            - string
          format: int32
        startUnit:
          pattern: ^-?(?:0|[1-9]\d*)$
          type:
            - integer
            - string
          format: int32
        endUnit:
          pattern: ^-?(?:0|[1-9]\d*)$
          type:
            - integer
            - string
          format: int32
        credits:
          type: string
        lessonId:
          type: string
    CourseErrorResponse:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
    CourseResultResponse:
      type: object
      properties:
        success:
          type: boolean
        data:
          type: array
          items:
            $ref: "#/components/schemas/CourseActivity"
        expirationTime:
          type: string
          format: date-time
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
    ErrorWithMessageResponse:
      type: object
      properties:
        message:
          type: string
        error:
          type: string
    ExamInfo:
      type: object
      properties:
        name:
          type: string
        time:
          type: string
        location:
          type: string
        seat:
          type: string
    ExamResponse:
      type: object
      properties:
        exams:
          type: array
          items:
            $ref: "#/components/schemas/ExamInfo"
        canClick:
          type: boolean
        error:
          type:
            - "null"
            - string
    LoginRequest:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
    LoginResponse:
      type: object
      properties:
        success:
          type: boolean
        studentId:
          type: string
        cookie:
          type: string
    PaymentData:
      type: object
      properties:
        records:
          type: array
          items:
            $ref: "#/components/schemas/PaymentModel"
        total:
          pattern: ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$
          type:
            - number
            - string
          format: double
    PaymentModel:
      required:
        - turnoverType
        - datetimeStr
        - resume
        - tranamt
      type: object
      properties:
        turnoverType:
          type: string
        datetimeStr:
          type: string
        resume:
          type: string
        tranamt:
          pattern: ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$
          type:
            - number
            - string
          format: double
    PlanCourse:
      type: object
      properties:
        name:
          type: string
        lessonType:
          type: string
        examMode:
          type: string
        courseTypeName:
          type: string
        credits:
          pattern: ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$
          type:
            - number
            - string
          format: double
        termStr:
          type: string
    ScoreResponse:
      type: object
      properties:
        name:
          maxLength: 64
          type: string
        lessonCode:
          maxLength: 64
          type: string
        lessonName:
          maxLength: 64
          type: string
        grade:
          maxLength: 64
          type: string
        gpa:
          maxLength: 64
          type: string
        gradeDetail:
          maxLength: 64
          type: string
        credit:
          maxLength: 64
          type: string
        isMinor:
          type: boolean
    SemesterItem:
      type: object
      properties:
        value:
          maxLength: 64
          type: string
        text:
          maxLength: 64
          type: string
    SemesterResult:
      type: object
      properties:
        data:
          type:
            - "null"
            - array
          items:
            $ref: "#/components/schemas/SemesterItem"
    TimeModel:
      type: object
      properties:
        startTime:
          type: string
        endTime:
          type: string
tags:
  - name: App
  - name: Bus
  - name: Course
  - name: Exam
  - name: Info
  - name: Login
  - name: Payment
  - name: Playground
  - name: Program
  - name: Score
